---
- hosts: control_plane
  become: yes
  tasks:

    - name: Remove pv-claim.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: absent
        src: ~/pv-claim.yml
        kubeconfig: "{{ k8s_config_file }}"

    - name: Remove pv-volume.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: absent
        src: ~/pv-volume.yml
        kubeconfig: "{{ k8s_config_file }}"

