---
- hosts: all
  become: yes
  tasks:

    - name: Make sure iSCSId and Open-iSCSId services are disabled
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - iscsid
        - open-iscsi
      ignore_errors: yes

    - name: Ubuntu specific tasks
      become: yes
      when: ansible_facts['distribution'] == 'Ubuntu'
      block:
        - name: Remove cloud-config to avoid boot delay
          apt:
            name: cloud-config
            state: absent

    - name: Update and upgrade apt packages (Debian and Ubuntu)
      when: ansible_os_family == 'Debian'
      shell:
        cmd: apt update && apt upgrade -y

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists == true

    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/homelab.pub

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'