---
- hosts: control_plane
  become: yes
  tasks:

    - name: Install python3-pip package
      package:
        name: "python3-pip"
        state: latest

    - name: Install kubernetes python package
      pip:
        name: kubernetes

    # Download and apply manifest
    - name: Download ingress-nginx manifest to the cluster.
      ansible.builtin.get_url:
        url: "{{ ingress_nginx_url }}"
        dest: ~/ingress-nginx.yaml
        mode: '0664'

    - name: Apply ingress-nginx manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: ~/ingress-nginx.yaml
        namespace: "{{ k8s_namespace }}"
        kubeconfig: "{{ k8s_config_file }}"

    - name: Copy namespace manifest
      ansible.builtin.template:
        src: namespace.j2
        dest: ~/namespace.yml

    - name: Apply namespace.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: ~/namespace.yml
        kubeconfig: "{{ k8s_config_file }}"

    - name: Copy storageClass manifest
      ansible.builtin.template:
        src: sc.yml
        dest: ~/sc.yml

    - name: Apply sc.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: ~/sc.yml
        kubeconfig: "{{ k8s_config_file }}"

    - name: Copy pv-volume.yml
      ansible.builtin.copy:
        src: pv.yml
        dest: ~/pv.yml

    - name: Apply pv.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: ~/pv.yml
        kubeconfig: "{{ k8s_config_file }}"

    - name: Copy pv-claim.yml
      ansible.builtin.template:
        src: pv-claim.j2
        dest: ~/pv-claim.yml

    - name: Apply pv-claim.yml manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: ~/pv-claim.yml
        kubeconfig: "{{ k8s_config_file }}"