---
kubernetes_version: "1.22.4-00"
pod_network_cidr: "10.244.0.0/16"

# Location of the k3s configuration file
k8s_config_file: "/home/ubuntu/.kube/config"

# ingress-nginx url
ingress_nginx_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/baremetal/deploy.yaml

ingress_nginx_cloud_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/cloud/deploy.yaml

k8s_namespace: "forgeops-7-1-1"

forgeops_namespace: "forgeops-7-1-1"