apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-ds-idrepo-0
  namespace: forgeops-7-1-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi